### ISSUE TITLE
Some YouTube videos throw an error

### ISSUE THREAD

**Issue by sullman** [plexinc-plugins/Services.bundle#211]
The video that came up in Plex Chat was `http://www.youtube.com/movie?v=vMvUeBrScqQ` (or you'll get the same problem swapping watch for movie, `http://www.youtube.com/watch?v=vMvUeBrScqQ`). I wasn't able to play that from my queue using Laika or Roku. When I tried to fake the requests with curl, here's what I got on the POST:

```
$curl -i --data-binary @/tmp/posturl "http://node.plexapp.com:32400/:/plugins/com.plexapp.system/serviceFunction/url/com.plexapp.plugins.youtube/YouTube/PlayVideo?args=Y2VyZWFsMQoxCmxpc3QKMApyMAo_&kwargs=Y2VyZWFsMQoxCmRpY3QKMgpzNDIKaHR0cDovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PXZNdlVlQnJTY3FRczMKdXJsczQKNzIwcHMxMQpkZWZhdWx0X2ZtdHIwCg__&indirect=1"
HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Server: nginx/0.8.54
Date: Fri, 30 Mar 2012 02:13:50 GMT
Connection: keep-alive
Content-Length: 2112

<?xml version='1.0' encoding='utf-8'?>
<Exception type="IndexError" message="list index out of range">
  <Traceback>Traceback (most recent call last):
  File "/data/node/shared/plex/bundle/com.plexapp.framework/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 594, in handle_request
    result = self._handle_private_request(pathNouns[1:], kwargs, context)
  File "/data/node/shared/plex/bundle/com.plexapp.framework/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 512, in _handle_private_request
    result = handler(pathNouns, kwargs, context)
  File "/data/node/shared/plex/bundle/com.plexapp.framework/Contents/Resources/Versions/2/Python/Framework/api/servicekit.py", line 425, in _services_request_handler
    result = self._core.services._call_named_function_in_service(f_name, service, f_args, f_kwargs, context = context)
  File "/data/node/shared/plex/bundle/com.plexapp.framework/Contents/Resources/Versions/2/Python/Framework/core.py", line 842, in _call_named_function_in_service
    result = host.call_named_function(fname, context=new_context, allow_deferred=allow_deferred, raise_exceptions=raise_exceptions, args=f_args, kwargs=f_kwargs)
  File "/data/node/shared/plex/bundle/com.plexapp.framework/Contents/Resources/Versions/2/Python/Framework/code.py", line 697, in call_named_function
    result = f(*args, **kwargs)
  File "/data/node/shared/plex/bundle/com.plexapp.framework/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 28, in __call__
    return self._f(*args, **kwargs)
  File "/data/node/releases/20120220211731/vendor/plex/bundle/com.plexapp.system.services/Contents/Service Sets/com.plexapp.plugins.youtube/URL/YouTube/ServiceCode.pys", line 164, in PlayVideo
    fmt_url_map = re.findall('"url_encoded_fmt_stream_map".+?"([^"]+)', yt_page)[0]
  File "/data/node/shared/plex/bundle/com.plexapp.framework/Contents/Resources/Versions/2/Python/Framework/bases.py", line 183, in &lt;lambda&gt;
    _getitem_ = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
</Traceback>
</Exception>
```

Just a stab in the dark, I haven't taken the time to get another data point, but perhaps there's something different about the Crackle videos available through YouTube that's messing things up.

**Comment by sander1** [comment]
Closed due to inactivity
